builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/dhcpd/main.go
    ldflags:
      - "-s -w"


release:
  prerelease: auto

universal_binaries:
  - replace: true
